//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buszules
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Buszules()
        {
            this.Busz = new HashSet<Busz>();
        }
    
        public int BuszulesID { get; set; }
        public int UlesID { get; set; }
        public Nullable<int> UtasID { get; set; }
        public bool Foglaltsag { get; set; }
        public int BuszID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Busz> Busz { get; set; }
        public virtual Ules Ules { get; set; }
        public virtual Utas Utas { get; set; }
    }
}
