//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Utazas
    {
        public int UtazasID { get; set; }
        public int UticelID { get; set; }
        public int DatumID { get; set; }
        public int BuszID { get; set; }
    
        public virtual Busz Busz { get; set; }
        public virtual Datum Datum { get; set; }
        public virtual Uticel Uticel { get; set; }
    }
}
