//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UtazasokEntities : DbContext
    {
        public UtazasokEntities()
            : base("name=UtazasokEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Busz> Busz { get; set; }
        public virtual DbSet<Buszules> Buszules { get; set; }
        public virtual DbSet<Datum> Datum { get; set; }
        public virtual DbSet<Ules> Ules { get; set; }
        public virtual DbSet<Utas> Utas { get; set; }
        public virtual DbSet<Utazas> Utazas { get; set; }
        public virtual DbSet<Uticel> Uticel { get; set; }
    }
}
